--GROUP BY ON VIEWS
SELECT * FROM TB_CUSTOMER_DATA;
SELECT * FROM TB_ORDER_DETAILS;
SELECT * FROM TB_PRODUCT_INFO;


CREATE OR REPLACE VIEW VIEW3GROUP_BY
AS
SELECT 
C.CUST_NAME,C.EMAIL,
P.PRODUCT_NAME,MAX(P.PRICE) AS MAXIMUM_SALARY
FROM TB_CUSTOMER_DATA C JOIN TB_ORDER_DETAILS O
ON (C.CUST_ID=O.CUST_ID)
JOIN TB_PRODUCT_INFO P
ON(O.PROD_ID=P.PROD_ID)
GROUP BY C.CUST_NAME,C.EMAIL,
P.PRODUCT_NAME
ORDER BY C.CUST_NAME;

SELECT *
FROM VIEW3GROUP_BY;
GRANT SELECT ON VIEW3GROUP_BY TO JAMES;
