CREATE TABLE TB_CUSTOMER_DATA(
 CUST_ID VARCHAR2(3) PRIMARY KEY,
 CUST_NAME VARCHAR2(50),
 PHONE NUMBER(10),
 EMAIL VARCHAR2(50) UNIQUE,
 ADDRESS VARCHAR2(60)
);

CREATE TABLE TB_PRODUCT_INFO(
 PROD_ID VARCHAR2(3) PRIMARY KEY,
 PRODUCT_NAME VARCHAR2(50),
 BRAND VARCHAR2(50),
 PRICE NUMBER(6)
);


CREATE TABLE TB_ORDER_DETAILS(
 ORDER_ID NUMBER(6) PRIMARY KEY,
 PROD_ID VARCHAR2(3),
 QUANTITY NUMBER(5),
 CUST_ID VARCHAR2(2),
 DISC_PERCENT NUMBER(2),
 PURCHASE_DATE DATE,
CONSTRAINT F_KEY_P FOREIGN KEY(PROD_ID) REFERENCES  TB_PRODUCT_INFO(PROD_ID) ON DELETE CASCADE,
CONSTRAINT F_KEY_C FOREIGN KEY(CUST_ID) REFERENCES  TB_CUSTOMER_DATA(CUST_ID) ON DELETE CASCADE
);











