--UPDATABLE VIEWS
--VIEWS SHOULD BE CREATED USING ONE TABLE

SELECT *FROM TB_PRODUCT_INFO;

CREATE OR REPLACE VIEW EXPENSIVE_PRODUCT_VIEW
AS
SELECT *FROM TB_PRODUCT_INFO
WHERE PRICE>1000;

SELECT *
FROM EXPENSIVE_PRODUCT_VIEW;


UPDATE EXPENSIVE_PRODUCT_VIEW
SET PRODUCT_NAME='Airpods white', BRAND='BOAT'
WHERE PROD_ID='P7';
--============================================================================



SELECT *
FROM ORDER_SUMMARY_VIEW;

--NOT UPDATABLE
--IF YOU HAVE CREATED VIEW FROM ONE AND MORE TABLE
--SUCH VIEWS CANNOT BE UPDATABLE
UPDATE ORDER_SUMMARY_VIEW
SET CUST_NAME='Rahul Gupta'
WHERE ORDER_ID=1;







