SELECT * FROM TB_CUSTOMER_DATA;
SELECT * FROM TB_PRODUCT_INFO;
SELECT * FROM TB_ORDER_DETAILS;

CREATE OR REPLACE VIEW VIEW1
AS
SELECT DISTINCT CUST_ID,CUST_NAME,PHONE,EMAIL
FROM TB_CUSTOMER_DATA;

SELECT *
FROM VIEW1;

CREATE OR REPLACE VIEW VIEW2
AS
SELECT  CUST_NAME,PHONE
FROM VIEW1;

SELECT *
FROM VIEW2;

UPDATE VIEW1
SET
CUST_NAME='Raj'
WHERE CUST_ID='C1';

GRANT SELECT ON VIEW2 TO JAMES;

--VIEW IS CREATED ON TOP OF VIEW.